package com.lseg_proy.accountsystem.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing an Account in the system.
 * It includes details about the account and its association with a User.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Account {

    /**
     * Unique identifier for the account.
     * It is automatically generated by the database when the account is created.
     */
    @Id
    @GeneratedValue
    private int accountId;

    /**
     * The name of the account.
     * This field is required and cannot be null.
     */
    @NotNull
    private String accountName;

    /**
     * The currency of the account.
     * This field is required and cannot be null.
     */
    @NotNull
    private String accountCurrency;

    /**
     * The user associated with this account.
     * Defined as a many-to-one relationship with the User entity.
     * Fetch type is LAZY, meaning it fetches the associated user data on demand.
     * The 'JsonBackReference' annotation prevents serialization issues during JSON conversion.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userId")
    @JsonBackReference
    private User user;
}
