package com.lseg_proy.accountsystem.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Entity representing a User in the system.
 * It includes details about the user and their associated accounts.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "\"user\"")
public class User {

    /**
     * Unique identifier for the user.
     * It is automatically generated by the database when the user is created.
     */
    @Id
    @GeneratedValue
    private int userId;

    /**
     * The name of the user.
     * This field is required and cannot be null.
     */
    @NotNull
    private String name;

    /**
     * The list of accounts associated with this user.
     * Defined as a one-to-many relationship with the Account entity.
     * Cascade type 'ALL' indicates that persistence actions (like save, delete) will
     * cascade from the user to its accounts.
     * Orphan removal is true, meaning if an account is removed from this list,
     * it will also be deleted from the database.
     * The 'JsonManagedReference' annotation is used to handle the bidirectional relationship
     * in JSON serialization/deserialization.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<Account> accounts;

}
